language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"


before_install:
  - sudo apt-get install bluetooth libbluetooth-dev python-tk

# Build script (If successfully built - no errors)
script: make

after_success:
  - python setup.py --version

deploy:
  provider: pypi
  user: "deven96"
  password: $PYPI_PASSWORD
  skip_existing: true
  condition: fork = false
  on:
    branch: master

after_deploy:
  - pip install signalum
  - python -c "import signalum"

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y
