language: python
python:
  - "3.6"


before_install:
  - sudo apt-get install bluetooth libbluetooth-dev

# Build script (If successfully built - no errors)
script:
  - pip install -r requirements.txt

after_success:
  - python setup.py --version

deploy:
  provider: pypi
  user: "deven96"
  password: $PYPI_PASSWORD
  condition: branch = master AND fork = false
  skip_existing: true

after_deploy:
  - pip install signalum
  - python -c "import signalum"

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y
