language: python
python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

# Command to install dependencies.
install:
  - pip install pipenv

# Build script (If successfully built - no errors)
script:
  - pipenv install

deploy:
  provider: pypi
  user: "deven96"
  password: $PYPI_PASSWORD
  all_branches: true
  condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  skip_existing: true

after_deploy:
  - pip install signalum
